# Generated by Django 3.1.4 on 2020-12-23 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='make',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autos.make'),
        ),
    ]
